//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.25 at 07:33:59 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.collada.org/2008/03/COLLADASchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package collada;
