//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.25 at 07:33:59 PM PDT 
//


package collada;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 * 			Opens a block of GLSL platform-specific data types and technique declarations.
 * 			
 * 
 * <p>Java class for profile_glsl_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="profile_glsl_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="asset" type="{http://www.collada.org/2008/03/COLLADASchema}asset_type" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="code" type="{http://www.collada.org/2008/03/COLLADASchema}fx_code_type"/>
 *           &lt;element name="include" type="{http://www.collada.org/2008/03/COLLADASchema}fx_include_type"/>
 *         &lt;/choice>
 *         &lt;element name="newparam" type="{http://www.collada.org/2008/03/COLLADASchema}glsl_newparam_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="technique" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="asset" type="{http://www.collada.org/2008/03/COLLADASchema}asset_type" minOccurs="0"/>
 *                   &lt;element name="annotate" type="{http://www.collada.org/2008/03/COLLADASchema}fx_annotate_type" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="pass" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="annotate" type="{http://www.collada.org/2008/03/COLLADASchema}fx_annotate_type" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="states" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;group ref="{http://www.collada.org/2008/03/COLLADASchema}gl_pipeline_settings_group" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="program" type="{http://www.collada.org/2008/03/COLLADASchema}glsl_program_type" minOccurs="0"/>
 *                             &lt;element name="evaluate" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="color_target" type="{http://www.collada.org/2008/03/COLLADASchema}fx_colortarget_type" maxOccurs="unbounded" minOccurs="0"/>
 *                                       &lt;element name="depth_target" type="{http://www.collada.org/2008/03/COLLADASchema}fx_depthtarget_type" maxOccurs="unbounded" minOccurs="0"/>
 *                                       &lt;element name="stencil_target" type="{http://www.collada.org/2008/03/COLLADASchema}fx_stenciltarget_type" maxOccurs="unbounded" minOccurs="0"/>
 *                                       &lt;element name="color_clear" type="{http://www.collada.org/2008/03/COLLADASchema}fx_clearcolor_type" maxOccurs="unbounded" minOccurs="0"/>
 *                                       &lt;element name="depth_clear" type="{http://www.collada.org/2008/03/COLLADASchema}fx_cleardepth_type" maxOccurs="unbounded" minOccurs="0"/>
 *                                       &lt;element name="stencil_clear" type="{http://www.collada.org/2008/03/COLLADASchema}fx_clearstencil_type" maxOccurs="unbounded" minOccurs="0"/>
 *                                       &lt;element name="draw" type="{http://www.collada.org/2008/03/COLLADASchema}fx_draw_type" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="extra" type="{http://www.collada.org/2008/03/COLLADASchema}extra_type" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="sid" type="{http://www.collada.org/2008/03/COLLADASchema}sid_type" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="extra" type="{http://www.collada.org/2008/03/COLLADASchema}extra_type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                 &lt;attribute name="sid" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}sid_type" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="extra" type="{http://www.collada.org/2008/03/COLLADASchema}extra_type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="platform" type="{http://www.w3.org/2001/XMLSchema}NCName" default="PC" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "profile_glsl_type", propOrder = {
    "asset",
    "codesAndIncludes",
    "newparams",
    "techniques",
    "extras"
})
public class ProfileGlslType {

    protected AssetType asset;
    @XmlElements({
        @XmlElement(name = "include", type = FxIncludeType.class),
        @XmlElement(name = "code", type = FxCodeType.class)
    })
    protected List<Object> codesAndIncludes;
    @XmlElement(name = "newparam")
    protected List<GlslNewparamType> newparams;
    @XmlElement(name = "technique", required = true)
    protected List<ProfileGlslType.Technique> techniques;
    @XmlElement(name = "extra")
    protected List<ExtraType> extras;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String platform;

    /**
     * Gets the value of the asset property.
     * 
     * @return
     *     possible object is
     *     {@link AssetType }
     *     
     */
    public AssetType getAsset() {
        return asset;
    }

    /**
     * Sets the value of the asset property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetType }
     *     
     */
    public void setAsset(AssetType value) {
        this.asset = value;
    }

    /**
     * Gets the value of the codesAndIncludes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the codesAndIncludes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCodesAndIncludes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FxIncludeType }
     * {@link FxCodeType }
     * 
     * 
     */
    public List<Object> getCodesAndIncludes() {
        if (codesAndIncludes == null) {
            codesAndIncludes = new ArrayList<Object>();
        }
        return this.codesAndIncludes;
    }

    /**
     * Gets the value of the newparams property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the newparams property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNewparams().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GlslNewparamType }
     * 
     * 
     */
    public List<GlslNewparamType> getNewparams() {
        if (newparams == null) {
            newparams = new ArrayList<GlslNewparamType>();
        }
        return this.newparams;
    }

    /**
     * Gets the value of the techniques property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the techniques property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTechniques().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProfileGlslType.Technique }
     * 
     * 
     */
    public List<ProfileGlslType.Technique> getTechniques() {
        if (techniques == null) {
            techniques = new ArrayList<ProfileGlslType.Technique>();
        }
        return this.techniques;
    }

    /**
     * Gets the value of the extras property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extras property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtras().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtraType }
     * 
     * 
     */
    public List<ExtraType> getExtras() {
        if (extras == null) {
            extras = new ArrayList<ExtraType>();
        }
        return this.extras;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the platform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatform() {
        if (platform == null) {
            return "PC";
        } else {
            return platform;
        }
    }

    /**
     * Sets the value of the platform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatform(String value) {
        this.platform = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="asset" type="{http://www.collada.org/2008/03/COLLADASchema}asset_type" minOccurs="0"/>
     *         &lt;element name="annotate" type="{http://www.collada.org/2008/03/COLLADASchema}fx_annotate_type" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="pass" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="annotate" type="{http://www.collada.org/2008/03/COLLADASchema}fx_annotate_type" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="states" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;group ref="{http://www.collada.org/2008/03/COLLADASchema}gl_pipeline_settings_group" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="program" type="{http://www.collada.org/2008/03/COLLADASchema}glsl_program_type" minOccurs="0"/>
     *                   &lt;element name="evaluate" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="color_target" type="{http://www.collada.org/2008/03/COLLADASchema}fx_colortarget_type" maxOccurs="unbounded" minOccurs="0"/>
     *                             &lt;element name="depth_target" type="{http://www.collada.org/2008/03/COLLADASchema}fx_depthtarget_type" maxOccurs="unbounded" minOccurs="0"/>
     *                             &lt;element name="stencil_target" type="{http://www.collada.org/2008/03/COLLADASchema}fx_stenciltarget_type" maxOccurs="unbounded" minOccurs="0"/>
     *                             &lt;element name="color_clear" type="{http://www.collada.org/2008/03/COLLADASchema}fx_clearcolor_type" maxOccurs="unbounded" minOccurs="0"/>
     *                             &lt;element name="depth_clear" type="{http://www.collada.org/2008/03/COLLADASchema}fx_cleardepth_type" maxOccurs="unbounded" minOccurs="0"/>
     *                             &lt;element name="stencil_clear" type="{http://www.collada.org/2008/03/COLLADASchema}fx_clearstencil_type" maxOccurs="unbounded" minOccurs="0"/>
     *                             &lt;element name="draw" type="{http://www.collada.org/2008/03/COLLADASchema}fx_draw_type" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="extra" type="{http://www.collada.org/2008/03/COLLADASchema}extra_type" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="sid" type="{http://www.collada.org/2008/03/COLLADASchema}sid_type" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="extra" type="{http://www.collada.org/2008/03/COLLADASchema}extra_type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *       &lt;attribute name="sid" use="required" type="{http://www.collada.org/2008/03/COLLADASchema}sid_type" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "asset",
        "annotates",
        "passes",
        "extras"
    })
    public static class Technique {

        protected AssetType asset;
        @XmlElement(name = "annotate")
        protected List<FxAnnotateType> annotates;
        @XmlElement(name = "pass", required = true)
        protected List<ProfileGlslType.Technique.Pass> passes;
        @XmlElement(name = "extra")
        protected List<ExtraType> extras;
        @XmlAttribute
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;
        @XmlAttribute(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String sid;

        /**
         * Gets the value of the asset property.
         * 
         * @return
         *     possible object is
         *     {@link AssetType }
         *     
         */
        public AssetType getAsset() {
            return asset;
        }

        /**
         * Sets the value of the asset property.
         * 
         * @param value
         *     allowed object is
         *     {@link AssetType }
         *     
         */
        public void setAsset(AssetType value) {
            this.asset = value;
        }

        /**
         * Gets the value of the annotates property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the annotates property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAnnotates().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FxAnnotateType }
         * 
         * 
         */
        public List<FxAnnotateType> getAnnotates() {
            if (annotates == null) {
                annotates = new ArrayList<FxAnnotateType>();
            }
            return this.annotates;
        }

        /**
         * Gets the value of the passes property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the passes property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPasses().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ProfileGlslType.Technique.Pass }
         * 
         * 
         */
        public List<ProfileGlslType.Technique.Pass> getPasses() {
            if (passes == null) {
                passes = new ArrayList<ProfileGlslType.Technique.Pass>();
            }
            return this.passes;
        }

        /**
         * Gets the value of the extras property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the extras property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExtras().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ExtraType }
         * 
         * 
         */
        public List<ExtraType> getExtras() {
            if (extras == null) {
                extras = new ArrayList<ExtraType>();
            }
            return this.extras;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the sid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSid() {
            return sid;
        }

        /**
         * Sets the value of the sid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSid(String value) {
            this.sid = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="annotate" type="{http://www.collada.org/2008/03/COLLADASchema}fx_annotate_type" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="states" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;group ref="{http://www.collada.org/2008/03/COLLADASchema}gl_pipeline_settings_group" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="program" type="{http://www.collada.org/2008/03/COLLADASchema}glsl_program_type" minOccurs="0"/>
         *         &lt;element name="evaluate" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="color_target" type="{http://www.collada.org/2008/03/COLLADASchema}fx_colortarget_type" maxOccurs="unbounded" minOccurs="0"/>
         *                   &lt;element name="depth_target" type="{http://www.collada.org/2008/03/COLLADASchema}fx_depthtarget_type" maxOccurs="unbounded" minOccurs="0"/>
         *                   &lt;element name="stencil_target" type="{http://www.collada.org/2008/03/COLLADASchema}fx_stenciltarget_type" maxOccurs="unbounded" minOccurs="0"/>
         *                   &lt;element name="color_clear" type="{http://www.collada.org/2008/03/COLLADASchema}fx_clearcolor_type" maxOccurs="unbounded" minOccurs="0"/>
         *                   &lt;element name="depth_clear" type="{http://www.collada.org/2008/03/COLLADASchema}fx_cleardepth_type" maxOccurs="unbounded" minOccurs="0"/>
         *                   &lt;element name="stencil_clear" type="{http://www.collada.org/2008/03/COLLADASchema}fx_clearstencil_type" maxOccurs="unbounded" minOccurs="0"/>
         *                   &lt;element name="draw" type="{http://www.collada.org/2008/03/COLLADASchema}fx_draw_type" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="extra" type="{http://www.collada.org/2008/03/COLLADASchema}extra_type" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="sid" type="{http://www.collada.org/2008/03/COLLADASchema}sid_type" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "annotates",
            "states",
            "program",
            "evaluate",
            "extras"
        })
        public static class Pass {

            @XmlElement(name = "annotate")
            protected List<FxAnnotateType> annotates;
            protected ProfileGlslType.Technique.Pass.States states;
            protected GlslProgramType program;
            protected ProfileGlslType.Technique.Pass.Evaluate evaluate;
            @XmlElement(name = "extra")
            protected List<ExtraType> extras;
            @XmlAttribute
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String sid;

            /**
             * Gets the value of the annotates property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the annotates property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAnnotates().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link FxAnnotateType }
             * 
             * 
             */
            public List<FxAnnotateType> getAnnotates() {
                if (annotates == null) {
                    annotates = new ArrayList<FxAnnotateType>();
                }
                return this.annotates;
            }

            /**
             * Gets the value of the states property.
             * 
             * @return
             *     possible object is
             *     {@link ProfileGlslType.Technique.Pass.States }
             *     
             */
            public ProfileGlslType.Technique.Pass.States getStates() {
                return states;
            }

            /**
             * Sets the value of the states property.
             * 
             * @param value
             *     allowed object is
             *     {@link ProfileGlslType.Technique.Pass.States }
             *     
             */
            public void setStates(ProfileGlslType.Technique.Pass.States value) {
                this.states = value;
            }

            /**
             * Gets the value of the program property.
             * 
             * @return
             *     possible object is
             *     {@link GlslProgramType }
             *     
             */
            public GlslProgramType getProgram() {
                return program;
            }

            /**
             * Sets the value of the program property.
             * 
             * @param value
             *     allowed object is
             *     {@link GlslProgramType }
             *     
             */
            public void setProgram(GlslProgramType value) {
                this.program = value;
            }

            /**
             * Gets the value of the evaluate property.
             * 
             * @return
             *     possible object is
             *     {@link ProfileGlslType.Technique.Pass.Evaluate }
             *     
             */
            public ProfileGlslType.Technique.Pass.Evaluate getEvaluate() {
                return evaluate;
            }

            /**
             * Sets the value of the evaluate property.
             * 
             * @param value
             *     allowed object is
             *     {@link ProfileGlslType.Technique.Pass.Evaluate }
             *     
             */
            public void setEvaluate(ProfileGlslType.Technique.Pass.Evaluate value) {
                this.evaluate = value;
            }

            /**
             * Gets the value of the extras property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the extras property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getExtras().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ExtraType }
             * 
             * 
             */
            public List<ExtraType> getExtras() {
                if (extras == null) {
                    extras = new ArrayList<ExtraType>();
                }
                return this.extras;
            }

            /**
             * Gets the value of the sid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSid() {
                return sid;
            }

            /**
             * Sets the value of the sid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSid(String value) {
                this.sid = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="color_target" type="{http://www.collada.org/2008/03/COLLADASchema}fx_colortarget_type" maxOccurs="unbounded" minOccurs="0"/>
             *         &lt;element name="depth_target" type="{http://www.collada.org/2008/03/COLLADASchema}fx_depthtarget_type" maxOccurs="unbounded" minOccurs="0"/>
             *         &lt;element name="stencil_target" type="{http://www.collada.org/2008/03/COLLADASchema}fx_stenciltarget_type" maxOccurs="unbounded" minOccurs="0"/>
             *         &lt;element name="color_clear" type="{http://www.collada.org/2008/03/COLLADASchema}fx_clearcolor_type" maxOccurs="unbounded" minOccurs="0"/>
             *         &lt;element name="depth_clear" type="{http://www.collada.org/2008/03/COLLADASchema}fx_cleardepth_type" maxOccurs="unbounded" minOccurs="0"/>
             *         &lt;element name="stencil_clear" type="{http://www.collada.org/2008/03/COLLADASchema}fx_clearstencil_type" maxOccurs="unbounded" minOccurs="0"/>
             *         &lt;element name="draw" type="{http://www.collada.org/2008/03/COLLADASchema}fx_draw_type" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "colorTargets",
                "depthTargets",
                "stencilTargets",
                "colorClears",
                "depthClears",
                "stencilClears",
                "draw"
            })
            public static class Evaluate {

                @XmlElement(name = "color_target")
                protected List<FxColortargetType> colorTargets;
                @XmlElement(name = "depth_target")
                protected List<FxDepthtargetType> depthTargets;
                @XmlElement(name = "stencil_target")
                protected List<FxStenciltargetType> stencilTargets;
                @XmlElement(name = "color_clear")
                protected List<FxClearcolorType> colorClears;
                @XmlElement(name = "depth_clear")
                protected List<FxCleardepthType> depthClears;
                @XmlElement(name = "stencil_clear")
                protected List<FxClearstencilType> stencilClears;
                protected String draw;

                /**
                 * Gets the value of the colorTargets property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the colorTargets property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getColorTargets().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link FxColortargetType }
                 * 
                 * 
                 */
                public List<FxColortargetType> getColorTargets() {
                    if (colorTargets == null) {
                        colorTargets = new ArrayList<FxColortargetType>();
                    }
                    return this.colorTargets;
                }

                /**
                 * Gets the value of the depthTargets property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the depthTargets property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getDepthTargets().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link FxDepthtargetType }
                 * 
                 * 
                 */
                public List<FxDepthtargetType> getDepthTargets() {
                    if (depthTargets == null) {
                        depthTargets = new ArrayList<FxDepthtargetType>();
                    }
                    return this.depthTargets;
                }

                /**
                 * Gets the value of the stencilTargets property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the stencilTargets property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getStencilTargets().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link FxStenciltargetType }
                 * 
                 * 
                 */
                public List<FxStenciltargetType> getStencilTargets() {
                    if (stencilTargets == null) {
                        stencilTargets = new ArrayList<FxStenciltargetType>();
                    }
                    return this.stencilTargets;
                }

                /**
                 * Gets the value of the colorClears property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the colorClears property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getColorClears().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link FxClearcolorType }
                 * 
                 * 
                 */
                public List<FxClearcolorType> getColorClears() {
                    if (colorClears == null) {
                        colorClears = new ArrayList<FxClearcolorType>();
                    }
                    return this.colorClears;
                }

                /**
                 * Gets the value of the depthClears property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the depthClears property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getDepthClears().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link FxCleardepthType }
                 * 
                 * 
                 */
                public List<FxCleardepthType> getDepthClears() {
                    if (depthClears == null) {
                        depthClears = new ArrayList<FxCleardepthType>();
                    }
                    return this.depthClears;
                }

                /**
                 * Gets the value of the stencilClears property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the stencilClears property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getStencilClears().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link FxClearstencilType }
                 * 
                 * 
                 */
                public List<FxClearstencilType> getStencilClears() {
                    if (stencilClears == null) {
                        stencilClears = new ArrayList<FxClearstencilType>();
                    }
                    return this.stencilClears;
                }

                /**
                 * Gets the value of the draw property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDraw() {
                    return draw;
                }

                /**
                 * Sets the value of the draw property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDraw(String value) {
                    this.draw = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;group ref="{http://www.collada.org/2008/03/COLLADASchema}gl_pipeline_settings_group" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "alphaFuncsAndBlendFuncsAndBlendFuncSeparates"
            })
            public static class States {

                @XmlElements({
                    @XmlElement(name = "color_mask", type = collada.CgPassType.States.ColorMask.class),
                    @XmlElement(name = "light_model_local_viewer_enable", type = collada.CgPassType.States.LightModelLocalViewerEnable.class),
                    @XmlElement(name = "clip_plane_enable", type = collada.CgPassType.States.ClipPlaneEnable.class),
                    @XmlElement(name = "polygon_mode", type = collada.CgPassType.States.PolygonMode.class),
                    @XmlElement(name = "color_material_enable", type = collada.CgPassType.States.ColorMaterialEnable.class),
                    @XmlElement(name = "point_smooth_enable", type = collada.CgPassType.States.PointSmoothEnable.class),
                    @XmlElement(name = "sample_coverage_enable", type = collada.CgPassType.States.SampleCoverageEnable.class),
                    @XmlElement(name = "blend_enable", type = collada.CgPassType.States.BlendEnable.class),
                    @XmlElement(name = "model_view_matrix", type = collada.CgPassType.States.ModelViewMatrix.class),
                    @XmlElement(name = "fog_enable", type = collada.CgPassType.States.FogEnable.class),
                    @XmlElement(name = "alpha_func", type = collada.CgPassType.States.AlphaFunc.class),
                    @XmlElement(name = "point_size_min", type = collada.CgPassType.States.PointSizeMin.class),
                    @XmlElement(name = "blend_func", type = collada.CgPassType.States.BlendFunc.class),
                    @XmlElement(name = "fog_coord_src", type = collada.CgPassType.States.FogCoordSrc.class),
                    @XmlElement(name = "texture_env_color", type = collada.CgPassType.States.TextureEnvColor.class),
                    @XmlElement(name = "logic_op_enable", type = collada.CgPassType.States.LogicOpEnable.class),
                    @XmlElement(name = "fog_end", type = collada.CgPassType.States.FogEnd.class),
                    @XmlElement(name = "rescale_normal_enable", type = collada.CgPassType.States.RescaleNormalEnable.class),
                    @XmlElement(name = "point_fade_threshold_size", type = collada.CgPassType.States.PointFadeThresholdSize.class),
                    @XmlElement(name = "stencil_mask_separate", type = collada.CgPassType.States.StencilMaskSeparate.class),
                    @XmlElement(name = "polygon_offset_line_enable", type = collada.CgPassType.States.PolygonOffsetLineEnable.class),
                    @XmlElement(name = "light_quadratic_attenuation", type = collada.CgPassType.States.LightQuadraticAttenuation.class),
                    @XmlElement(name = "depth_bounds", type = collada.CgPassType.States.DepthBounds.class),
                    @XmlElement(name = "textureRECT_enable", type = collada.CgPassType.States.TextureRECTEnable.class),
                    @XmlElement(name = "depth_range", type = collada.CgPassType.States.DepthRange.class),
                    @XmlElement(name = "depth_clamp_enable", type = collada.CgPassType.States.DepthClampEnable.class),
                    @XmlElement(name = "normalize_enable", type = collada.CgPassType.States.NormalizeEnable.class),
                    @XmlElement(name = "fog_color", type = collada.CgPassType.States.FogColor.class),
                    @XmlElement(name = "material_emission", type = collada.CgPassType.States.MaterialEmission.class),
                    @XmlElement(name = "light_diffuse", type = collada.CgPassType.States.LightDiffuse.class),
                    @XmlElement(name = "dither_enable", type = collada.CgPassType.States.DitherEnable.class),
                    @XmlElement(name = "color_material", type = collada.CgPassType.States.ColorMaterial.class),
                    @XmlElement(name = "sample_alpha_to_one_enable", type = collada.CgPassType.States.SampleAlphaToOneEnable.class),
                    @XmlElement(name = "stencil_op_separate", type = collada.CgPassType.States.StencilOpSeparate.class),
                    @XmlElement(name = "fog_density", type = collada.CgPassType.States.FogDensity.class),
                    @XmlElement(name = "clip_plane", type = collada.CgPassType.States.ClipPlane.class),
                    @XmlElement(name = "texture1D", type = collada.CgPassType.States.Texture1D.class),
                    @XmlElement(name = "polygon_offset_point_enable", type = collada.CgPassType.States.PolygonOffsetPointEnable.class),
                    @XmlElement(name = "blend_equation_separate", type = collada.CgPassType.States.BlendEquationSeparate.class),
                    @XmlElement(name = "light_ambient", type = collada.CgPassType.States.LightAmbient.class),
                    @XmlElement(name = "stencil_func", type = collada.CgPassType.States.StencilFunc.class),
                    @XmlElement(name = "material_specular", type = collada.CgPassType.States.MaterialSpecular.class),
                    @XmlElement(name = "fog_start", type = collada.CgPassType.States.FogStart.class),
                    @XmlElement(name = "alpha_test_enable", type = collada.CgPassType.States.AlphaTestEnable.class),
                    @XmlElement(name = "stencil_func_separate", type = collada.CgPassType.States.StencilFuncSeparate.class),
                    @XmlElement(name = "textureRECT", type = collada.CgPassType.States.TextureRECT.class),
                    @XmlElement(name = "depth_test_enable", type = collada.CgPassType.States.DepthTestEnable.class),
                    @XmlElement(name = "stencil_mask", type = collada.CgPassType.States.StencilMask.class),
                    @XmlElement(name = "texture_env_mode", type = collada.CgPassType.States.TextureEnvMode.class),
                    @XmlElement(name = "projection_matrix", type = collada.CgPassType.States.ProjectionMatrix.class),
                    @XmlElement(name = "polygon_offset_fill_enable", type = collada.CgPassType.States.PolygonOffsetFillEnable.class),
                    @XmlElement(name = "line_stipple", type = collada.CgPassType.States.LineStipple.class),
                    @XmlElement(name = "texture2D_enable", type = collada.CgPassType.States.Texture2DEnable.class),
                    @XmlElement(name = "cull_face_enable", type = collada.CgPassType.States.CullFaceEnable.class),
                    @XmlElement(name = "light_spot_exponent", type = collada.CgPassType.States.LightSpotExponent.class),
                    @XmlElement(name = "textureDEPTH_enable", type = collada.CgPassType.States.TextureDEPTHEnable.class),
                    @XmlElement(name = "light_model_two_side_enable", type = collada.CgPassType.States.LightModelTwoSideEnable.class),
                    @XmlElement(name = "polygon_smooth_enable", type = collada.CgPassType.States.PolygonSmoothEnable.class),
                    @XmlElement(name = "material_shininess", type = collada.CgPassType.States.MaterialShininess.class),
                    @XmlElement(name = "light_constant_attenuation", type = collada.CgPassType.States.LightConstantAttenuation.class),
                    @XmlElement(name = "texture3D", type = collada.CgPassType.States.Texture3D.class),
                    @XmlElement(name = "texture1D_enable", type = collada.CgPassType.States.Texture1DEnable.class),
                    @XmlElement(name = "light_enable", type = collada.CgPassType.States.LightEnable.class),
                    @XmlElement(name = "polygon_offset", type = collada.CgPassType.States.PolygonOffset.class),
                    @XmlElement(name = "depth_bounds_enable", type = collada.CgPassType.States.DepthBoundsEnable.class),
                    @XmlElement(name = "stencil_op", type = collada.CgPassType.States.StencilOp.class),
                    @XmlElement(name = "scissor", type = collada.CgPassType.States.Scissor.class),
                    @XmlElement(name = "point_size_max", type = collada.CgPassType.States.PointSizeMax.class),
                    @XmlElement(name = "light_linear_attenuation", type = collada.CgPassType.States.LightLinearAttenuation.class),
                    @XmlElement(name = "line_smooth_enable", type = collada.CgPassType.States.LineSmoothEnable.class),
                    @XmlElement(name = "line_stipple_enable", type = collada.CgPassType.States.LineStippleEnable.class),
                    @XmlElement(name = "light_model_color_control", type = collada.CgPassType.States.LightModelColorControl.class),
                    @XmlElement(name = "sample_alpha_to_coverage_enable", type = collada.CgPassType.States.SampleAlphaToCoverageEnable.class),
                    @XmlElement(name = "texture3D_enable", type = collada.CgPassType.States.Texture3DEnable.class),
                    @XmlElement(name = "shade_model", type = collada.CgPassType.States.ShadeModel.class),
                    @XmlElement(name = "depth_mask", type = collada.CgPassType.States.DepthMask.class),
                    @XmlElement(name = "blend_equation", type = collada.CgPassType.States.BlendEquation.class),
                    @XmlElement(name = "scissor_test_enable", type = collada.CgPassType.States.ScissorTestEnable.class),
                    @XmlElement(name = "point_size", type = collada.CgPassType.States.PointSize.class),
                    @XmlElement(name = "stencil_test_enable", type = collada.CgPassType.States.StencilTestEnable.class),
                    @XmlElement(name = "color_logic_op_enable", type = collada.CgPassType.States.ColorLogicOpEnable.class),
                    @XmlElement(name = "textureDEPTH", type = collada.CgPassType.States.TextureDEPTH.class),
                    @XmlElement(name = "material_ambient", type = collada.CgPassType.States.MaterialAmbient.class),
                    @XmlElement(name = "depth_func", type = collada.CgPassType.States.DepthFunc.class),
                    @XmlElement(name = "texture2D", type = collada.CgPassType.States.Texture2D.class),
                    @XmlElement(name = "textureCUBE", type = collada.CgPassType.States.TextureCUBE.class),
                    @XmlElement(name = "light_position", type = collada.CgPassType.States.LightPosition.class),
                    @XmlElement(name = "light_model_ambient", type = collada.CgPassType.States.LightModelAmbient.class),
                    @XmlElement(name = "line_width", type = collada.CgPassType.States.LineWidth.class),
                    @XmlElement(name = "material_diffuse", type = collada.CgPassType.States.MaterialDiffuse.class),
                    @XmlElement(name = "light_specular", type = collada.CgPassType.States.LightSpecular.class),
                    @XmlElement(name = "light_spot_cutoff", type = collada.CgPassType.States.LightSpotCutoff.class),
                    @XmlElement(name = "point_distance_attenuation", type = collada.CgPassType.States.PointDistanceAttenuation.class),
                    @XmlElement(name = "blend_color", type = collada.CgPassType.States.BlendColor.class),
                    @XmlElement(name = "textureCUBE_enable", type = collada.CgPassType.States.TextureCUBEEnable.class),
                    @XmlElement(name = "multisample_enable", type = collada.CgPassType.States.MultisampleEnable.class),
                    @XmlElement(name = "light_spot_direction", type = collada.CgPassType.States.LightSpotDirection.class),
                    @XmlElement(name = "cull_face", type = collada.CgPassType.States.CullFace.class),
                    @XmlElement(name = "front_face", type = collada.CgPassType.States.FrontFace.class),
                    @XmlElement(name = "polygon_stipple_enable", type = collada.CgPassType.States.PolygonStippleEnable.class),
                    @XmlElement(name = "lighting_enable", type = collada.CgPassType.States.LightingEnable.class),
                    @XmlElement(name = "logic_op", type = collada.CgPassType.States.LogicOp.class),
                    @XmlElement(name = "blend_func_separate", type = collada.CgPassType.States.BlendFuncSeparate.class),
                    @XmlElement(name = "fog_mode", type = collada.CgPassType.States.FogMode.class)
                })
                protected List<Object> alphaFuncsAndBlendFuncsAndBlendFuncSeparates;

                /**
                 * Gets the value of the alphaFuncsAndBlendFuncsAndBlendFuncSeparates property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the alphaFuncsAndBlendFuncsAndBlendFuncSeparates property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getAlphaFuncsAndBlendFuncsAndBlendFuncSeparates().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link collada.CgPassType.States.ColorMask }
                 * {@link collada.CgPassType.States.LightModelLocalViewerEnable }
                 * {@link collada.CgPassType.States.ClipPlaneEnable }
                 * {@link collada.CgPassType.States.PolygonMode }
                 * {@link collada.CgPassType.States.ColorMaterialEnable }
                 * {@link collada.CgPassType.States.PointSmoothEnable }
                 * {@link collada.CgPassType.States.SampleCoverageEnable }
                 * {@link collada.CgPassType.States.BlendEnable }
                 * {@link collada.CgPassType.States.ModelViewMatrix }
                 * {@link collada.CgPassType.States.FogEnable }
                 * {@link collada.CgPassType.States.AlphaFunc }
                 * {@link collada.CgPassType.States.PointSizeMin }
                 * {@link collada.CgPassType.States.BlendFunc }
                 * {@link collada.CgPassType.States.FogCoordSrc }
                 * {@link collada.CgPassType.States.TextureEnvColor }
                 * {@link collada.CgPassType.States.LogicOpEnable }
                 * {@link collada.CgPassType.States.FogEnd }
                 * {@link collada.CgPassType.States.RescaleNormalEnable }
                 * {@link collada.CgPassType.States.PointFadeThresholdSize }
                 * {@link collada.CgPassType.States.StencilMaskSeparate }
                 * {@link collada.CgPassType.States.PolygonOffsetLineEnable }
                 * {@link collada.CgPassType.States.LightQuadraticAttenuation }
                 * {@link collada.CgPassType.States.DepthBounds }
                 * {@link collada.CgPassType.States.TextureRECTEnable }
                 * {@link collada.CgPassType.States.DepthRange }
                 * {@link collada.CgPassType.States.DepthClampEnable }
                 * {@link collada.CgPassType.States.NormalizeEnable }
                 * {@link collada.CgPassType.States.FogColor }
                 * {@link collada.CgPassType.States.MaterialEmission }
                 * {@link collada.CgPassType.States.LightDiffuse }
                 * {@link collada.CgPassType.States.DitherEnable }
                 * {@link collada.CgPassType.States.ColorMaterial }
                 * {@link collada.CgPassType.States.SampleAlphaToOneEnable }
                 * {@link collada.CgPassType.States.StencilOpSeparate }
                 * {@link collada.CgPassType.States.FogDensity }
                 * {@link collada.CgPassType.States.ClipPlane }
                 * {@link collada.CgPassType.States.Texture1D }
                 * {@link collada.CgPassType.States.PolygonOffsetPointEnable }
                 * {@link collada.CgPassType.States.BlendEquationSeparate }
                 * {@link collada.CgPassType.States.LightAmbient }
                 * {@link collada.CgPassType.States.StencilFunc }
                 * {@link collada.CgPassType.States.MaterialSpecular }
                 * {@link collada.CgPassType.States.FogStart }
                 * {@link collada.CgPassType.States.AlphaTestEnable }
                 * {@link collada.CgPassType.States.StencilFuncSeparate }
                 * {@link collada.CgPassType.States.TextureRECT }
                 * {@link collada.CgPassType.States.DepthTestEnable }
                 * {@link collada.CgPassType.States.StencilMask }
                 * {@link collada.CgPassType.States.TextureEnvMode }
                 * {@link collada.CgPassType.States.ProjectionMatrix }
                 * {@link collada.CgPassType.States.PolygonOffsetFillEnable }
                 * {@link collada.CgPassType.States.LineStipple }
                 * {@link collada.CgPassType.States.Texture2DEnable }
                 * {@link collada.CgPassType.States.CullFaceEnable }
                 * {@link collada.CgPassType.States.LightSpotExponent }
                 * {@link collada.CgPassType.States.TextureDEPTHEnable }
                 * {@link collada.CgPassType.States.LightModelTwoSideEnable }
                 * {@link collada.CgPassType.States.PolygonSmoothEnable }
                 * {@link collada.CgPassType.States.MaterialShininess }
                 * {@link collada.CgPassType.States.LightConstantAttenuation }
                 * {@link collada.CgPassType.States.Texture3D }
                 * {@link collada.CgPassType.States.Texture1DEnable }
                 * {@link collada.CgPassType.States.LightEnable }
                 * {@link collada.CgPassType.States.PolygonOffset }
                 * {@link collada.CgPassType.States.DepthBoundsEnable }
                 * {@link collada.CgPassType.States.StencilOp }
                 * {@link collada.CgPassType.States.Scissor }
                 * {@link collada.CgPassType.States.PointSizeMax }
                 * {@link collada.CgPassType.States.LightLinearAttenuation }
                 * {@link collada.CgPassType.States.LineSmoothEnable }
                 * {@link collada.CgPassType.States.LineStippleEnable }
                 * {@link collada.CgPassType.States.LightModelColorControl }
                 * {@link collada.CgPassType.States.SampleAlphaToCoverageEnable }
                 * {@link collada.CgPassType.States.Texture3DEnable }
                 * {@link collada.CgPassType.States.ShadeModel }
                 * {@link collada.CgPassType.States.DepthMask }
                 * {@link collada.CgPassType.States.BlendEquation }
                 * {@link collada.CgPassType.States.ScissorTestEnable }
                 * {@link collada.CgPassType.States.PointSize }
                 * {@link collada.CgPassType.States.StencilTestEnable }
                 * {@link collada.CgPassType.States.ColorLogicOpEnable }
                 * {@link collada.CgPassType.States.TextureDEPTH }
                 * {@link collada.CgPassType.States.MaterialAmbient }
                 * {@link collada.CgPassType.States.DepthFunc }
                 * {@link collada.CgPassType.States.Texture2D }
                 * {@link collada.CgPassType.States.TextureCUBE }
                 * {@link collada.CgPassType.States.LightPosition }
                 * {@link collada.CgPassType.States.LightModelAmbient }
                 * {@link collada.CgPassType.States.LineWidth }
                 * {@link collada.CgPassType.States.MaterialDiffuse }
                 * {@link collada.CgPassType.States.LightSpecular }
                 * {@link collada.CgPassType.States.LightSpotCutoff }
                 * {@link collada.CgPassType.States.PointDistanceAttenuation }
                 * {@link collada.CgPassType.States.BlendColor }
                 * {@link collada.CgPassType.States.TextureCUBEEnable }
                 * {@link collada.CgPassType.States.MultisampleEnable }
                 * {@link collada.CgPassType.States.LightSpotDirection }
                 * {@link collada.CgPassType.States.CullFace }
                 * {@link collada.CgPassType.States.FrontFace }
                 * {@link collada.CgPassType.States.PolygonStippleEnable }
                 * {@link collada.CgPassType.States.LightingEnable }
                 * {@link collada.CgPassType.States.LogicOp }
                 * {@link collada.CgPassType.States.BlendFuncSeparate }
                 * {@link collada.CgPassType.States.FogMode }
                 * 
                 * 
                 */
                public List<Object> getAlphaFuncsAndBlendFuncsAndBlendFuncSeparates() {
                    if (alphaFuncsAndBlendFuncsAndBlendFuncSeparates == null) {
                        alphaFuncsAndBlendFuncsAndBlendFuncSeparates = new ArrayList<Object>();
                    }
                    return this.alphaFuncsAndBlendFuncsAndBlendFuncSeparates;
                }

            }

        }

    }

}
