//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.25 at 07:33:59 PM PDT 
//


package collada;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for kinematics_model_technique_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="kinematics_model_technique_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="newparam" type="{http://www.collada.org/2008/03/COLLADASchema}kinematics_newparam_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="instance_joint" type="{http://www.collada.org/2008/03/COLLADASchema}instance_joint_type"/>
 *           &lt;element name="joint" type="{http://www.collada.org/2008/03/COLLADASchema}joint_type"/>
 *         &lt;/choice>
 *         &lt;element name="link" type="{http://www.collada.org/2008/03/COLLADASchema}link_type" maxOccurs="unbounded"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="formula" type="{http://www.collada.org/2008/03/COLLADASchema}formula_type"/>
 *           &lt;element name="instance_formula" type="{http://www.collada.org/2008/03/COLLADASchema}instance_formula_type"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "kinematics_model_technique_type", propOrder = {
    "newparams",
    "instanceJointsAndJoints",
    "links",
    "formulasAndInstanceFormulas"
})
public class KinematicsModelTechniqueType {

    @XmlElement(name = "newparam")
    protected List<KinematicsNewparamType> newparams;
    @XmlElements({
        @XmlElement(name = "instance_joint", type = InstanceJointType.class),
        @XmlElement(name = "joint", type = JointType.class)
    })
    protected List<Object> instanceJointsAndJoints;
    @XmlElement(name = "link", required = true)
    protected List<LinkType> links;
    @XmlElements({
        @XmlElement(name = "formula", type = FormulaType.class),
        @XmlElement(name = "instance_formula", type = InstanceFormulaType.class)
    })
    protected List<Object> formulasAndInstanceFormulas;

    /**
     * Gets the value of the newparams property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the newparams property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNewparams().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KinematicsNewparamType }
     * 
     * 
     */
    public List<KinematicsNewparamType> getNewparams() {
        if (newparams == null) {
            newparams = new ArrayList<KinematicsNewparamType>();
        }
        return this.newparams;
    }

    /**
     * Gets the value of the instanceJointsAndJoints property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instanceJointsAndJoints property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstanceJointsAndJoints().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstanceJointType }
     * {@link JointType }
     * 
     * 
     */
    public List<Object> getInstanceJointsAndJoints() {
        if (instanceJointsAndJoints == null) {
            instanceJointsAndJoints = new ArrayList<Object>();
        }
        return this.instanceJointsAndJoints;
    }

    /**
     * Gets the value of the links property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the links property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LinkType }
     * 
     * 
     */
    public List<LinkType> getLinks() {
        if (links == null) {
            links = new ArrayList<LinkType>();
        }
        return this.links;
    }

    /**
     * Gets the value of the formulasAndInstanceFormulas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formulasAndInstanceFormulas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormulasAndInstanceFormulas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FormulaType }
     * {@link InstanceFormulaType }
     * 
     * 
     */
    public List<Object> getFormulasAndInstanceFormulas() {
        if (formulasAndInstanceFormulas == null) {
            formulasAndInstanceFormulas = new ArrayList<Object>();
        }
        return this.formulasAndInstanceFormulas;
    }

}
