//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.25 at 07:33:59 PM PDT 
//


package collada;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			The mesh element contains vertex and primitive information sufficient to describe basic geometric meshes.
 * 			
 * 
 * <p>Java class for mesh_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mesh_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="source" type="{http://www.collada.org/2008/03/COLLADASchema}source_type" maxOccurs="unbounded"/>
 *         &lt;element name="vertices" type="{http://www.collada.org/2008/03/COLLADASchema}vertices_type"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="lines" type="{http://www.collada.org/2008/03/COLLADASchema}lines_type"/>
 *           &lt;element name="linestrips" type="{http://www.collada.org/2008/03/COLLADASchema}linestrips_type"/>
 *           &lt;element name="polygons" type="{http://www.collada.org/2008/03/COLLADASchema}polygons_type"/>
 *           &lt;element name="polylist" type="{http://www.collada.org/2008/03/COLLADASchema}polylist_type"/>
 *           &lt;element name="triangles" type="{http://www.collada.org/2008/03/COLLADASchema}triangles_type"/>
 *           &lt;element name="trifans" type="{http://www.collada.org/2008/03/COLLADASchema}trifans_type"/>
 *           &lt;element name="tristrips" type="{http://www.collada.org/2008/03/COLLADASchema}tristrips_type"/>
 *         &lt;/choice>
 *         &lt;element name="extra" type="{http://www.collada.org/2008/03/COLLADASchema}extra_type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mesh_type", propOrder = {
    "sources",
    "vertices",
    "linesAndLinestripsAndPolygons",
    "extras"
})
public class MeshType {

    @XmlElement(name = "source", required = true)
    protected List<SourceType> sources;
    @XmlElement(required = true)
    protected VerticesType vertices;
    @XmlElements({
        @XmlElement(name = "linestrips", type = LinestripsType.class),
        @XmlElement(name = "lines", type = LinesType.class),
        @XmlElement(name = "polylist", type = PolylistType.class),
        @XmlElement(name = "trifans", type = TrifansType.class),
        @XmlElement(name = "polygons", type = PolygonsType.class),
        @XmlElement(name = "tristrips", type = TristripsType.class),
        @XmlElement(name = "triangles", type = TrianglesType.class)
    })
    protected List<Object> linesAndLinestripsAndPolygons;
    @XmlElement(name = "extra")
    protected List<ExtraType> extras;

    /**
     * Gets the value of the sources property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sources property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSources().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SourceType }
     * 
     * 
     */
    public List<SourceType> getSources() {
        if (sources == null) {
            sources = new ArrayList<SourceType>();
        }
        return this.sources;
    }

    /**
     * Gets the value of the vertices property.
     * 
     * @return
     *     possible object is
     *     {@link VerticesType }
     *     
     */
    public VerticesType getVertices() {
        return vertices;
    }

    /**
     * Sets the value of the vertices property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerticesType }
     *     
     */
    public void setVertices(VerticesType value) {
        this.vertices = value;
    }

    /**
     * Gets the value of the linesAndLinestripsAndPolygons property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linesAndLinestripsAndPolygons property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinesAndLinestripsAndPolygons().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LinestripsType }
     * {@link LinesType }
     * {@link PolylistType }
     * {@link TrifansType }
     * {@link PolygonsType }
     * {@link TristripsType }
     * {@link TrianglesType }
     * 
     * 
     */
    public List<Object> getLinesAndLinestripsAndPolygons() {
        if (linesAndLinestripsAndPolygons == null) {
            linesAndLinestripsAndPolygons = new ArrayList<Object>();
        }
        return this.linesAndLinestripsAndPolygons;
    }

    /**
     * Gets the value of the extras property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extras property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtras().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtraType }
     * 
     * 
     */
    public List<ExtraType> getExtras() {
        if (extras == null) {
            extras = new ArrayList<ExtraType>();
        }
        return this.extras;
    }

}
