//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.25 at 07:33:59 PM PDT 
//


package collada;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for physics_scene_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="physics_scene_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="asset" type="{http://www.collada.org/2008/03/COLLADASchema}asset_type" minOccurs="0"/>
 *         &lt;element name="instance_force_field" type="{http://www.collada.org/2008/03/COLLADASchema}instance_force_field_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="instance_physics_model" type="{http://www.collada.org/2008/03/COLLADASchema}instance_physics_model_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="technique_common">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="gravity" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float3_type" minOccurs="0"/>
 *                   &lt;element name="time_step" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="technique" type="{http://www.collada.org/2008/03/COLLADASchema}technique_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="extra" type="{http://www.collada.org/2008/03/COLLADASchema}extra_type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}token" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "physics_scene_type", propOrder = {
    "asset",
    "instanceForceFields",
    "instancePhysicsModels",
    "techniqueCommon",
    "techniques",
    "extras"
})
public class PhysicsSceneType {

    protected AssetType asset;
    @XmlElement(name = "instance_force_field")
    protected List<InstanceForceFieldType> instanceForceFields;
    @XmlElement(name = "instance_physics_model")
    protected List<InstancePhysicsModelType> instancePhysicsModels;
    @XmlElement(name = "technique_common", required = true)
    protected PhysicsSceneType.TechniqueCommon techniqueCommon;
    @XmlElement(name = "technique")
    protected List<TechniqueType> techniques;
    @XmlElement(name = "extra")
    protected List<ExtraType> extras;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String name;

    /**
     * Gets the value of the asset property.
     * 
     * @return
     *     possible object is
     *     {@link AssetType }
     *     
     */
    public AssetType getAsset() {
        return asset;
    }

    /**
     * Sets the value of the asset property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetType }
     *     
     */
    public void setAsset(AssetType value) {
        this.asset = value;
    }

    /**
     * Gets the value of the instanceForceFields property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instanceForceFields property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstanceForceFields().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstanceForceFieldType }
     * 
     * 
     */
    public List<InstanceForceFieldType> getInstanceForceFields() {
        if (instanceForceFields == null) {
            instanceForceFields = new ArrayList<InstanceForceFieldType>();
        }
        return this.instanceForceFields;
    }

    /**
     * Gets the value of the instancePhysicsModels property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instancePhysicsModels property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstancePhysicsModels().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstancePhysicsModelType }
     * 
     * 
     */
    public List<InstancePhysicsModelType> getInstancePhysicsModels() {
        if (instancePhysicsModels == null) {
            instancePhysicsModels = new ArrayList<InstancePhysicsModelType>();
        }
        return this.instancePhysicsModels;
    }

    /**
     * Gets the value of the techniqueCommon property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicsSceneType.TechniqueCommon }
     *     
     */
    public PhysicsSceneType.TechniqueCommon getTechniqueCommon() {
        return techniqueCommon;
    }

    /**
     * Sets the value of the techniqueCommon property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicsSceneType.TechniqueCommon }
     *     
     */
    public void setTechniqueCommon(PhysicsSceneType.TechniqueCommon value) {
        this.techniqueCommon = value;
    }

    /**
     * Gets the value of the techniques property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the techniques property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTechniques().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TechniqueType }
     * 
     * 
     */
    public List<TechniqueType> getTechniques() {
        if (techniques == null) {
            techniques = new ArrayList<TechniqueType>();
        }
        return this.techniques;
    }

    /**
     * Gets the value of the extras property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extras property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtras().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtraType }
     * 
     * 
     */
    public List<ExtraType> getExtras() {
        if (extras == null) {
            extras = new ArrayList<ExtraType>();
        }
        return this.extras;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="gravity" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float3_type" minOccurs="0"/>
     *         &lt;element name="time_step" type="{http://www.collada.org/2008/03/COLLADASchema}targetable_float_type" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "gravity",
        "timeStep"
    })
    public static class TechniqueCommon {

        protected TargetableFloat3Type gravity;
        @XmlElement(name = "time_step")
        protected TargetableFloatType timeStep;

        /**
         * Gets the value of the gravity property.
         * 
         * @return
         *     possible object is
         *     {@link TargetableFloat3Type }
         *     
         */
        public TargetableFloat3Type getGravity() {
            return gravity;
        }

        /**
         * Sets the value of the gravity property.
         * 
         * @param value
         *     allowed object is
         *     {@link TargetableFloat3Type }
         *     
         */
        public void setGravity(TargetableFloat3Type value) {
            this.gravity = value;
        }

        /**
         * Gets the value of the timeStep property.
         * 
         * @return
         *     possible object is
         *     {@link TargetableFloatType }
         *     
         */
        public TargetableFloatType getTimeStep() {
            return timeStep;
        }

        /**
         * Sets the value of the timeStep property.
         * 
         * @param value
         *     allowed object is
         *     {@link TargetableFloatType }
         *     
         */
        public void setTimeStep(TargetableFloatType value) {
            this.timeStep = value;
        }

    }

}
